name: Build release zip

on:
  workflow_run:
    workflows: [Static Analysis]
    types: [completed]

jobs:

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Restore npm dependency cache
        uses: ./.github/actions/restore-npm-cache

      - name: Install npm dependencies and build scripts
        run: |
          npm install
          npm run build

      - name: Install PHP-Scoper
        run: |
          wget -O /usr/local/bin/php-scoper https://github.com/humbug/php-scoper/releases/download/0.18.2/php-scoper.phar
          chmod +x /usr/local/bin/php-scoper

      - name: Install composer dependencies
        run: composer run phpscoper

      - name: Generate zip
        run: |
          composer global require wp-cli/wp-cli-bundle
          composer global require wp-cli/dist-archive-command
          /home/runner/.composer/vendor/bin/wp dist-archive ./ ${{ github.event.repository.name }}

      - name: Unzip the archive (prevents double zip problem)
        id: unzip
        run: unzip ${{ github.event.repository.name }}.zip -d zipfile
        shell: bash

      - name: Upload the archive as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: zipfile
          retention-days: 5

      # - name: Generate zip
      #   uses: 10up/action-wordpress-plugin-build-zip@stable
      #   env:
      #     SLUG: omniform # needed until we're live in the plugin directory.


  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'